# Generated by Django 6.0.1 on 2026-01-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
