# Generated by Django 6.0.1 on 2026-01-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscore',
            name='insights',
            field=models.TextField(blank=True),
        ),
    ]
